### ISSUE TITLE
로그인 PostMapping 관련 이슈

### ISSUE THREAD

**Issue by hightuv** [kookmin-sw/capstone-2024-32#23]
현재 "/login"에 PostMapping 해놓은 부분이 안 돌아갑니다.
나름대로 조사를 해보았는데, UserDetails의 loadUserByUsername을 overriding헀기 때문에 로그인 PostMapping쪽 처리는 스프링 시큐리티가 해주는 것으로 확인됩니다.
PostMapping 부분은 상의해보고 없애도 될 것 같네요.

**Comment by moonwonki** [comment]
Issue 내용을 분석해본 결과, GetMapping까지는 연결이 되어 있으나, PostMapping의 경우 스프링 Security에 의해 Overide 되어 저희가 만든 코드로 아예 진입하지 않는 것으로 보입니다. 따라서 완전히 구조를 바꾸고자 합니다.

로그인 방식에 대한 세밀한 수정은 Authentication Manager를 상속 구현하는 것으로 수정이 가능한 것 같습니다.
다만 이미 견고하게 짜여진 Spring Security의 기본 틀을 최대한 건드리지 않는 선에서 단지 사용자 화면에 추가적인 정보를 전달하는 것은 SuccessHandler와 FailureHandler만으로도 가능하기에 해당 방법을 사용해서 고치겠습니다. 

SuccessHandler와 FailureHandler는 각각 로그인 성공 시와 실패 시 동작을 정리한 것으로 저희가 원하는 것은 각각의 행동에 로그를 남기는 것과 fail시 화면에 정보를 전달하는 것입니다.

해당 내용을 반영하여 구조를 개편한 뒤 '로그인 관련 #23 이슈 해결' 브랜치에 업로드 하겠습니다.
